In [44]:
# 4. Utwórz klasę Martix. Wykorzystaj całą wiedzę jaką posiadasz na temat macierzy. Zdefiniuj wszystkie znane Ci operacje.
import numpy as np
import numpy.linalg as npl 

class Matrix:
    def __init__(self, matrix):
        self.matrix = np.matrix(matrix)
        
    def __multiplication__(self, matrix):        
        return self.matrix * np.matrix(matrix)
    
    def __add__(self, matrix):
        return self.matrix + np.matrix(matrix)
    
    def __subtraction__(self, matrix):
        return self.matrix - np.matrix(matrix)
    
    def __exponentiation__(self, power):
        return sel.matrix**power
    
    def __transpose__(self):
        return np.transpose(self.matrix)
    
    def __inverse__(self):
        return npl.inv(self.matrix)
    
    def __equations__(self, free_elements):
        return npl.solve(self.matrix, np.matrix(free_elements))
        
matrix = Matrix( ((2, 3), (3, 5)) )

In [35]:
# Mnożenie macierzy przez macierz
matrix.__multiplication__( ((1, 2), (5, -1)) )

matrix([[17,  1],
        [28,  1]])

In [36]:
# Dodawanie 2 macierzy
matrix.__add__( ((1, 2), (5, -1)) )

matrix([[3, 5],
        [8, 4]])

In [33]:
# Odejmowanie 2 macierzy
matrix.__subtraction__( ((1, 2), (5, -1)) )

matrix([[ 1,  1],
        [-2,  6]])

In [37]:
# Potęgowanie macierzy
matrix.__subtraction__(4)

matrix([[-2, -1],
        [-1,  1]])

In [41]:
# Macież transponowana
matrix.__transpose__()

matrix([[2, 3],
        [3, 5]])

In [43]:
# Macierz odwrtotna
matrix.__inverse__()

matrix([[ 5., -3.],
        [-3.,  2.]])

In [47]:
# Obliczanie układów równań
matrix.__equations__( ((0, 0)) )

ValueError: solve: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m,n)->(m,n) (size 1 is different from 2)