In [54]:
#3. Utwórz klasę Vector3D. Wykorzystaj całą wiedzę jaką posiadasz na temat wektorów w przestrzeni. Zdefiniuj wszystkie znane Ci operacje.
import numpy as np 

class Vector3D:
    def __init__(self, x, y, z):
        self.x = float(x)
        self.y = float(y)
        self.z = float(z)
        
    def __vectoLength__(self):
        return (self.x**2 + self.y**2 + self.z**2)**0.5
    
    def __sum__(self, x):
        vector1 = np.array([self.x, self.y, self.z])
        vector2 = np.array(x)
        
        return vector1 + vector2
    
    def __subtraction__(self, x):
        vector1 = np.array([self.x, self.y, self.z])
        vector2 = np.array(x)
        
        return vector1 - vector2
    
    def __scalarMultiplication__(self, x):
        vector1 = np.array([self.x, self.y, self.z])
        vector2 = np.array(x)
        
        return np.dot(vector1, vector2)
    
    def __vectorMultiplication__(self, x):
        vector1 = np.array([self.x, self.y, self.z])
        vector2 = np.array(x)
        
        return np.cross(vector1, vector2)
    
    def __multiplicationByNumber__(self, number):
        return np.array([self.x, self.y, self.z]) * number
        
vector3d = Vector3D(2, 3, 1)

In [45]:
# Długość wektora
vector3d.__vectoLength__()

3.7416573867739413

In [46]:
# Suma 2 wektorów
vector3d.__sum__([4, 6, 8])

array([6., 9., 9.])

In [47]:
# Różnica 2 wektorów
vector3d.__subtraction__([4, 6, 8])

array([-2., -3., -7.])

In [48]:
# Iloczyn skalarny
vector3d.__scalarMultiplication__([4, 6, 8])

34.0

In [49]:
# Iloczyn wektorowy
vector3d.__vectorMultiplication__([4, 6, 8])

array([ 18., -12.,   0.])

In [55]:
# Własności własne wektora
vector3d.__multiplicationByNumber__(12)

array([24., 36., 12.])